def iteracionTipoDato():
    iteracion = input('Ingresa un valor cualquiera: ')
    print("Este tipo de dato en Python es:")
    print(type(iteracion))
    iteracion = input('Segunda Interacción, ingrese un valor cualquiera: ')
    print("Este tipo de dato en Python es:")
    print(type(iteracion))
    iteracion = input('Tercera Interacción, ingrese un valor cualquiera: ')
    print("Este tipo de dato en Python es:")
    print(type(iteracion))
    iteracion = input('Cuarta Interacción, ingrese un valor cualquiera: ')
    print("Este tipo de dato en Python es:")
    print(type(iteracion))
    iteracion = input('Ingresa un valor cualquiera: ')
    print("Este tipo de dato en Python es:")
    print(type(iteracion))
    print("Se acabo las iteraciones")